SCREEN_WIDTH = 1400
SCREEN_HEIGHT = 900
PLAYER_BULLET_X_OFFSETS = [-15, 15]
PLAYER_BULLET_Y = 15
FRAME_TIME_MS = 16  # TODO change this later

ENEMY_SPEED = 3  # pix/frame
ENEMY_BULLET_X_OFFSETS = [0, 45]
PLAYER_SPEED = 10
